# -*- js -*-
{
    "version": "2.1",

    "jobs": {
        "build": {
            "docker": [{"image": "debian:stable"}],
            "steps": [
                "checkout",
                {"run": "echo lmao!!!!"},
            ]
        },
    },

    "workflows": {
        "version": 2,
        "all": {
            "jobs": ["build"]
        }
    }
}
